---
- name: Cisco Backup Config
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
        backup_options:
          dir_path: /etc/configs/backup/
      register: config_output

    - debug:
        var: config_output