---
- name: Cisco Backup Config
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: check the running-config against master config
      ios_config:
        diff_against: intended
#        intended_config: "/etc/configs/golden/{{inventory_hostname}}_golden.cfg"
        intended_config: "/etc/configs/golden/{{inventory_hostname}}_golden.cfg"
#      register: config_drift

#    - debug:
#        msg: "{{config_drift}}"