---
- name: Cisco Backup Config
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: check the running-config against master config
      ios_config:
        diff_against: intended
        intended_config: "/etc/configs/golden/{{inventory_hostname}}_golden.cfg"
      register: config_drift

#    - debug:
#        msg: "{{config_drift}}"
    - name: Send Email with Report
      mail:
        host: smtp.office365.com
        port: 587
        username: "{{ email_address }}"
        password: "{{ email_account_password }}"
        from: "{{ email_address }}"
        to: "{{ email_address }}"
        subject: "Configuration Drift Report"
        body: "Consolidated configuration drift report {{ config_drift }}"
      delegate_to: localhost
      run_once: yes