---
- name: Cisco Backup Config
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ENSURE THAT THE DESIRED SNMP STRINGS ARE PRESENT
      ios_config:
        commands:
          - snmp-server community $YCSNMPV2RO$ RO 99