- name: Update Banners
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no
  
  tasks:
  - name: configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present
    
