---
- name: Update Syslog
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: configure host logging NY
          cisco.ios.ios_logging:
            dest: host
            name: 172.16.0.1
            state: present
      when: "{{region}}" == "NY"
      
    - name: configure host logging NJ
          cisco.ios.ios_logging:
            dest: host
            name: 172.16.0.2
            state: present
      when: "{{region}}" == "NJ"
      
    - name: configure host logging HK
          cisco.ios.ios_logging:
            dest: host
            name: 172.16.0.3
            state: present
      when: "{{region}}" == "HK"
