---
- name: update local admin accounts
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: create a new user
      cisco.nxos.nxos_user:
        name: ansible
        sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
