---
- name: Update NTP for nxos
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Update NTP for nxos
      cisco.nxos.nxos_ntp:
          server: 1.2.3.4
          key_id: 32
          prefer: enabled
          host: '{{ inventory_hostname }}'
          username: '{{ un }}'
          password: '{{ pwd }}'
