---
- name: Update NTP for nxos
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Update NTP for nxos NY
      nxos_ntp:
          server: 172.16.0.1
          key_id: 32
          prefer: enabled
          host: '{{ inventory_hostname }}'
          username: '{{ un }}'
          password: '{{ pwd }}'
      when: "{{region}}" == "NY"
      
    - name: Update NTP for nxos NJ
      nxos_ntp:
          server: 172.16.0.2
          key_id: 32
          prefer: enabled
          host: '{{ inventory_hostname }}'
          username: '{{ un }}'
          password: '{{ pwd }}'
      when: "{{region}}" == "NJ"
      
    - name: Update NTP for nxos HK
      nxos_ntp:
          server: 172.16.0.3
          key_id: 32
          prefer: enabled
          host: '{{ inventory_hostname }}'
          username: '{{ un }}'
          password: '{{ pwd }}'
      when: "{{region}}" == "HK"
